// ============================================================
// Build-time content sync.
//   • Learn feed  -> src/data/learn.js   (blog + podcast RSS)
//   • Events tab  -> src/data/events.js  (The Events Calendar API)
//
// Runs automatically before every build (see package.json).
// Each source is independent: if one can't be reached, the build
// keeps the last generated file so it never fails.
// ============================================================

import { XMLParser } from 'fast-xml-parser'
import { toEventGroups } from './lib/events-transform.js'
import { writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const LEARN_OUT = join(__dirname, '..', 'src', 'data', 'learn.js')
const EVENTS_OUT = join(__dirname, '..', 'src', 'data', 'events.js')

const BLOG_FEED = 'https://helponechild.org/feed/'
const PODCAST_FEED = 'https://helponechild.org/podcast/feed/'
const EVENTS_API = 'https://helponechild.org/wp-json/tribe/events/v1/events'
const MAX_EACH = 8

const parser = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: '@_' })

function stripHtml(s = '') {
  return String(s)
    .replace(/<[^>]*>/g, ' ')
    .replace(/&#8217;|&#039;|&#39;/g, "'")
    .replace(/&#8220;|&#8221;/g, '"')
    .replace(/&#8230;/g, '…')
    .replace(/&amp;/g, '&')
    .replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

function truncate(s, n = 160) {
  if (s.length <= n) return s
  return s.slice(0, n).replace(/\s+\S*$/, '') + '…'
}

function fmtDate(pubDate) {
  const d = new Date(pubDate)
  if (isNaN(d)) return ''
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
}

function asItems(feedXml) {
  const doc = parser.parse(feedXml)
  const items = doc?.rss?.channel?.item
  if (!items) return []
  return Array.isArray(items) ? items : [items]
}

async function spotifyLink(item) {
  for (const h of [item['content:encoded'], item.description]) {
    const m = typeof h === 'string' && h.match(/open\.spotify\.com\/embed\/episode\/([A-Za-z0-9]+)/)
    if (m) return `https://open.spotify.com/episode/${m[1]}`
  }
  try {
    const page = await (await fetch(item.link)).text()
    const m = page.match(/open\.spotify\.com\/embed\/episode\/([A-Za-z0-9]+)/)
    if (m) return `https://open.spotify.com/episode/${m[1]}`
  } catch { /* ignore */ }
  return item.link
}

const BANNER = () =>
  '// AUTO-GENERATED by scripts/sync-content.js — do not edit by hand.\n' +
  `// Last synced: ${new Date().toISOString()}\n\n`

// ---- Learn feed (blog + podcast) ----
async function syncLearn() {
  const [blogXml, podXml] = await Promise.all([
    fetch(BLOG_FEED).then((r) => r.text()),
    fetch(PODCAST_FEED).then((r) => r.text()),
  ])

  const blog = asItems(blogXml).slice(0, MAX_EACH).map((it) => ({
    type: 'blog',
    date: fmtDate(it.pubDate),
    title: stripHtml(String(it.title)),
    blurb: truncate(stripHtml(it.description || '')),
    link: it.link,
  }))

  const podcasts = []
  for (const it of asItems(podXml).slice(0, MAX_EACH)) {
    podcasts.push({
      type: 'podcast',
      date: fmtDate(it.pubDate),
      title: stripHtml(String(it.title)),
      blurb: truncate(stripHtml(it.description || '')),
      link: await spotifyLink(it),
    })
  }

  const all = [...podcasts, ...blog].filter((x) => x.title && x.link)
  if (all.length === 0) throw new Error('feeds returned no usable items')
  writeFileSync(LEARN_OUT, BANNER() + 'export const learnItems = ' + JSON.stringify(all, null, 2) + '\n')
  console.log(`[sync] learn: ${podcasts.length} podcasts + ${blog.length} blog posts`)
}

// ---- Events (The Events Calendar API, upcoming only) ----
async function syncEvents() {
  const startParam = new Date().toISOString().slice(0, 10) // today, YYYY-MM-DD
  const url = `${EVENTS_API}?per_page=30&start_date=${startParam}`
  const data = await (await fetch(url)).json()
  const groups = toEventGroups(data.events || [], new Date())
  if (groups.length === 0) throw new Error('no upcoming events returned')
  writeFileSync(EVENTS_OUT, BANNER() + 'export const events = ' + JSON.stringify(groups, null, 2) + '\n')
  const count = groups.reduce((n, g) => n + g.items.length, 0)
  console.log(`[sync] events: ${count} upcoming events`)
}

// Run both independently — one failing (or being offline) never breaks the
// build, as long as a previously generated file exists to fall back to.
async function run(name, fn, outPath) {
  try {
    await fn()
  } catch (err) {
    console.warn(`[sync] ${name}: could not refresh (${err.message})`)
    if (existsSync(outPath)) {
      console.warn(`[sync] keeping existing ${outPath} — build will continue.`)
    } else {
      console.error(`[sync] no existing ${outPath} to fall back to.`)
      process.exitCode = 1
    }
  }
}

await run('learn', syncLearn, LEARN_OUT)
await run('events', syncEvents, EVENTS_OUT)
